First bit of the reimplementation as kaocha.api
This is a second iteration on the recursive test runner I spiked earlier, this
time driven by specs and tests, and built bottom-up.

It introduces the three core data structures: config, test plan, result, and the
two multimethods that are at the hard of the transformation from each type to
the next, load-testable and run-testable.

CONFIG ---[load-testables]--> TEST PLAN --[run-testables]--> RESULT

Testables are nested and extensible, out of the box Kaocha will come with a
:kaocha.type/suite, which contains :kaocha.type/ns, which contains
:kaocha.type/var.

diff --git a/bin/cider b/bin/cider
--- a/bin/cider
+++ b/bin/cider
@@ -3,7 +3,23 @@
 set +e
 
 export NREPL_PORT=$(( RANDOM % 1000 + 7000 ))
-echo "Starting nREPL on port" $NREPL_PORT
+
+CIDER_VERSION=${CIDER_VERSION:-$(emacsclient -e '(upcase cider-version) 2> /dev/null')}
+CLJR_VERSION=$(emacsclient -e '(when (package-installed-p (quote clj-refactor))
+                                 (replace-regexp-in-string "snapshot" "-SNAPSHOT"
+                                   (pkg-info-format-version
+                                     (pkg-info-library-version (quote clj-refactor)))))')
+
+if [[ ! $CIDER_VERSION = *'"' ]]; then
+    CIDER_VERSION='"'$CIDER_VERSION'"'
+fi
+
+if [[ -z "$CIDER_VERSION" ]]; then
+    echo "Failed to get CIDER version. Is the Emacs CIDER package installed?"
+    exit 1
+fi
+
+echo "Starting cider/cider-nrepl $CIDER_VERSION on port $NREPL_PORT"
 
 bash <<EOF &
   while ! nc -z localhost $NREPL_PORT ; do echo -n '.' ; sleep 1; done
@@ -13,22 +29,10 @@ EOF
 EMACSCLIENT=$!
 
 finish() {
-  [[ -z "$EMACSCLIENT" ]] || kill -TERM "$EMACSCLIENT" 2>/dev/null
+    [[ -z "$EMACSCLIENT" ]] || kill -TERM "$EMACSCLIENT" 2>/dev/null
 }
 
 trap finish EXIT
-
-CIDER_VERSION=$(emacsclient -e '(upcase cider-version) 2> /dev/null')
-CLJR_VERSION=$(emacsclient -e '(when (package-installed-p (quote clj-refactor))
-                                 (replace-regexp-in-string "snapshot" "-SNAPSHOT"
-                                   (pkg-info-format-version
-                                     (pkg-info-library-version (quote clj-refactor)))))')
-
-
-if [[ -z "$CIDER_VERSION" ]]; then
-    echo "Failed to get CIDER version. Is the Emacs CIDER package installed?"
-    exit 1
-fi
 
 clj                                                                      \
     -A:dev                                                               \
